### ISSUE TITLE
Support ARM architecture

### ISSUE THREAD

**Issue by gaiar** [conda-forge/toolchain3-feedstock#4]
Part of code 
`if [ ! -z "$ARCH" ]
then
    export CONDA_FORGE_CFLAGS="${CONDA_FORGE_CFLAGS} -m${ARCH}"
    export CONDA_FORGE_CXXFLAGS="${CONDA_FORGE_CXXFLAGS} -m${ARCH}"
fi`

on Raspberry Pi 3 leads to error `error: C compiler cannot create executables` because of -marmv7l what is not supported by gcc 

supported flags: 
https://gcc.gnu.org/onlinedocs/gcc-8.1.0/gcc/ARM-Options.html#ARM-Options
https://gist.github.com/fm4dd/c663217935dc17f0fc73c9c81b0aa845

**Comment by jakirkham** [comment]
This package is deprecated would switch to `defaults` compilers if you have a chance. Also would raise an issue on the feedstock(s) where they were using this package.

**Comment by jakirkham** [comment]
The ARM discussion is in issue ( https://github.com/conda-forge/conda-forge.github.io/issues/269 ). So closing to consolidate into that discussion.
